@startuml
set separator ::

enum ge::CubeFace {
	Front  	Back
	Left   	Right
	Top    	Bottom
	All
}
hide CubeFace methods

class ge::GeometryData {
	+positions: Vec3[]
	+colors: Vec3[]
	+uvs: Vec2[]
	+normals: Vec3[]
	..
	+indices: uint[]
}
hide GeometryData methods

class ge::GeometryGenerator {
	{static} +GenerateCube(faces) : GeometryData
	{static} +GenerateIcosphere(subdivisions) : GeometryData
	--
	{static} -SubdivideTriangle(t) : Vec3[3][4]
	{static} -AppendSubdivedTriangle(triangleVector, t, subdivisions)
}
hide GeometryGenerator fields

class ge::GeometryTransform {
	{static} +ApplyMatrix(&gd, matrix)
	..
	{static} +Scale(&gd, scale)
	{static} +Rotate(&gd, angle, axis)
	{static} +Translate(&gd, translation)
	..
	{static} +ApplyColor(&gd, color)
}
hide GeometryTransform fields

GeometryGenerator <-right- CubeFace

GeometryData <.up. GeometryGenerator
GeometryData <-right- GeometryTransform

@enduml
