@startuml
set separator ::

enum ge::CubeFace {
	Front  	Back
	Left   	Right
	Top    	Bottom
	All
}
hide CubeFace methods

class ge::GeometryData {
	+positions, colors, uvs, normals
	+indices
}
hide GeometryData methods

class ge::GeometryGenerator {
	{static} +GenerateCube()
	{static} +GenerateIcosphere()
}
hide GeometryGenerator fields

class ge::GeometryTransform {
	{static} +ApplyMatrix()
	..
	{static} +Scale()
	{static} +Rotate()
	{static} +Translate()
	..
	{static} +ApplyColor()
}
hide GeometryTransform fields

GeometryGenerator <-right- CubeFace

GeometryData <.up. GeometryGenerator
GeometryData <-right- GeometryTransform

@enduml
