@startuml
set separator ::

enum gm::GameState {
	MenuMain
	MenuOptions
	MenuLevels
	ScenePlaying
	ScenePaused
}
hide GameState methods

class gm::Game {
	+onInit(width, height, internalWidth, internalHeight, resource)
	+onUpdate(deltaTime, currentTime, resource, input) : bool
	+onRender(deltaTime, currentTime, resource)
	+onResize(width, height)
	..
	+getState() : GameState
	+setState(state)
	--
	-setStateMenuMain()
	-setStateMenuOptions()
	-setStateMenuLevels()
	-setStateScenePlaying()
	-setStateScenePaused()
	..
	-state: GameState
	..
	-internalSize: Vec2
	-gui: GUI
	-scene: Scene
}

class gm::Scene {
	+createFromFile(fileName, resource) : bool
	+restart()
	+destroy()
	..
	+updateCamera(deltaYaw, deltaPitch, deltaDistance)
	+updateMazeRotation(deltaPitch, deltaRoll)
	+updatePhysics(deltaTime)
	..
	+checkWinCondition() : bool
	+getTime() : float
	..
	+setProjection(fov, aspect)
	+display()
	+shoudPlaySound() : bool
	--
	-marbleBlockCollision(x, y, z, deltaTime)
	..
	{static} -DistanceSphereAABB(box, sphere) : float
	..
	-timer: float
	..
	-camera: Camera
	-renderables: Renderable[]
	-lights: Light[]
	..
	-marble: Marble
	-maze: Maze
	-start, finish, initCameraValues: Vec3
	..
	-cameraDistance, cameraYaw, cameraPitch: float
	-marbleIsTouchingWalls: bool[3]
	-marbleWasTouchingWalls: bool[3]
}

enum gm::BlockType {
	Empty
	Wall
	Start
	Finish
}
hide BlockType methods

class gm::Maze {
	+create(initBlocks)
	..
	+getBlock(x, y, z) : BlockType
	+setBlock(x, y, z, block)
	..
	+toGeometry() : GeometryData
	..
	+getWidth() : int
	+getHeight() : int
	+getDepth() : int
	..
	+transform: Mat4
	--
	-width, height, depth: int
	-blocks: BlockType[]
}

class gm::Marble {
	+toGeometry() : GeometryData
	..
	+transform: Mat4
	..
	+position: Vec3
	+velocity: Vec3
	+direction: Vec3
	+radius: float
	+speed: float
}

Maze <-down- BlockType

Scene *-left- Maze
Scene *-down- Marble

Game <-left- GameState
Game <-- Scene

@enduml
