@startuml
set separator ::

class rn::GUI {
	+create()
	+setFrame()
	..
	+addLabel()
	+getLabelText()
	+setLabelText()
	+removeLabel()
	..
	+addButton()
	+checkButtonSelected()
	+removeButton()
	..
	+display()
	+clear()
	--
	-shader, font, mesh
	..
	-labels
	-buttons
}

enum rn::TextAlign {
	Center
	Left
	Right
	Bottom
	Top
}
hide TextAlign methods

class rn::Label {
	+create()
	..
	+text
	+position, size, color
}

class rn::Button {
	+create()
	..
	+isInside()
	..
	+selected
	..
	+position, size
	+back, selectedBack
}

Label <-- TextAlign

GUI *-left- Label
GUI *-down- Button

@enduml
