@startuml
set separator ::

class rn::GUI {
	+create(&shader, &font, &mesh)
	+setFrame(left, right, bottom, top)
	..
	+addLabel(name) : &Label
	+removeLabel(name)
	..
	+addButton(name, ...) : &Button
	+checkButtonSelected(name, x, y) : bool
	+getButtonSelected(name) : bool
	+setButtonSelected(name, isSelected)
	+removeButton(name)
	..
	+display()
	+clear()
	--
	-updateMesh()
	..
	-frame: Vec4
	..
	-shader: &Shader
	-font: &Font
	-mesh: &Mesh
	..
	-labels: map<str, Label>
	-buttons: map<str, Button>
	..
	-needsUpdate: bool
}

enum rn::TextAlign {
	Center
	Left
	Right
	Bottom
	Top
}
hide TextAlign methods

class rn::Label {
	+create(size, text, position, color, align)
	..
	+text: string
	+position, size: Vec2
	+color: Vec4
	+align: uint
}

class rn::Button {
	+create(&label, back, selectedBack, margin)
	..
	+isInside(x, y)
	..
	+selected: bool
	..
	+position, size: Vec2
	+back, selectedBack: Vec4
}

Label <-- TextAlign

GUI *-left- Label
GUI *-down- Button

@enduml
