@startuml
set separator ::

enum in::KeyState {
	Released
	Pressed
	JustReleased
	JustPressed
}
hide KeyState methods

enum in::KeyName {
	Quit
	Restart
	Pause
	MazeRollDecrease
	MazeRollIncrease
	MazeYawDecrease
	MazeYawIncrease
}
hide KeyName methods

class in::Input {
	{static} +KeyboardValues : int[]
	..
	+getKey(key) : KeyState
	+getMouseL() : KeyState
	+getMouseR() : KeyState
	..
	+setKey(key, state)
	+setMouseL(state)
	+setMouseR(state)
	..
	+getMouseX() : float
	+getMouseY() : float
	+getDeltaMouseX() : float
	+getDeltaMouseY() : float
	+setMousePos(x, y)
	..
	+getScrollX() : float
	+getScrollY() : float
	+setScroll(x, y)
	--
	-keyboard: KeyState[]
	-mouseL: KeyState
	-mouseR: KeyState
	-mouseX, mouseY: float
	-lastMouseX, lastMouseY: float
	-scrollX, scrollY: float
}

Input <-left- KeyState
Input <-right- KeyName

@enduml
