@startuml
set separator ::

class la::Vec2 {
	+x, y
}
hide Vec2 methods

class la::Vec4 {
	+x, y, z, w
}
hide Vec4 methods

class la::Vec3 {
	+normalize()
	+cross()
	+dot()
	+length()
	..
	+x, y, z
}

class la::Mat4 {
	{static} +Identity()
	{static} +Scale()
	{static} +Rotate()
	{static} +Translate()
	..
	{static} +LookAt()
	{static} +Project2d()
	{static} +Project3d()
	..
	+transpose()
	+inverse()
	..
	+x1, ... , w4
}

@enduml
