@startuml
set separator ::

class lin::Vec2 {
	+x: float
	+y: float
}
hide Vec2 methods

class lin::Vec4 {
	+x: float
	+y: float
	+z: float
	+w: float
}
hide Vec4 methods

class lin::Vec3 {
	+normalize() : Vec3
	+cross(vec) : Vec3
	+dot(vec) : float
	+length() : float
	..
	+x: float
	+y: float
	+z: float
}

class lin::Mat4 {
	{static} +Identity() : Mat4
	{static} +Scale(scale) : Mat4
	{static} +Rotate(angle, axis) : Mat4
	{static} +Translate(translation) : Mat4
	..
	{static} +LookAt(eye, target, up) : Mat4
	{static} +Project2d(left, right, bottom, top, near, far) : Mat4
	{static} +Project3d(fov, aspect, near, far) : Mat4
	..
	+x1, ... , w4: float
}

@enduml
