@startuml
set separator ::

class rn::Renderable {
	+create()
	..
	+tag
	+mesh
	+material
	+transform
}

class rn::Camera {
	+project2d()
	+project3d()
	..
	+setPosition()
	+setTarget()
	+setUp()
	..
	+getPosition()
	+getTarget()
	+getUp()
	..
	+getViewMatrix()
	+getProjectionMatrix()
	--
	-pos, target, up
	..
	-view, projection
}

class rn::Light {
	+position
	..
	+ambient
	+diffuse
	+specular
}
hide Light methods

class rn::Renderer {
	{static} +clear()
	{static} +render()
	..
	{static} +resizeFrame()
}
hide Renderer fields

Renderer <-down- Camera
Renderer <-right- Renderable
Renderer <-left- Light

@enduml
