@startuml
set separator ::

class ren::RenderAssetManager {
	+initFromConfig(fileName)
	..
	+createShader(name) : &Shader
	+createTexture(name) : &Texture
	+createMaterial(name) : &Material
	+createMesh(name) : &Mesh
	+destroy()
	..
	+getShader(name) : &Shader
	+getTexture(name) : &Texture
	+getMaterial(name) : &Material
	+getMesh(name) : &Mesh
	--
	-stringToShader(configLine)
	-stringToTexture(configLine)
	-stringToMaterial(configLine1, configLine2)
	..
	-shaders: map<str, Shader>
	-textures: map<str, Texture>
	-materials: map<str, Material>
	-meshes: map<str, Mesh>
}

class ren::Renderable {
	+create(&mesh, &material)
	..
	+mesh: &Mesh
	+material: &Material
	+transform: Mat4
}

class ren::Camera {
	+project2d(left, right, bottom, top, near, far)
	+project3d(fov, aspect, near, far)
	..
	+setPosition(pos)
	+setTarget(target)
	+setUp(up)
	..
	+getPosition() : Vec3
	+getTarget() : Vec3
	+getUp() : Vec3
	..
	+getViewMatrix() : Mat4
	+getProjectionMatrix() : Mat4
	--
	-updateViewMatrix()
	..
	-pos: Vec3
	-target: Vec3
	-up: Vec3
	..
	-view: Mat4
	-projection: Mat4
}

class ren::Light {
	+position: Vec3
	..
	+ambient: Vec3
	+diffuse: Vec3
	+specular: Vec3
}
hide Light methods

class ren::Renderer {
	{static} +clear(red, green, blue)
	{static} +render(&renderable)
	{static} +render(&camera, &renderables[], &lights[])
	..
	{static} +resizeFrame(width, height)
}
hide Renderer fields

Renderable <-down- RenderAssetManager

Renderer <-down- Camera
Renderer <-left- Renderable
Renderer <-right- Light

@enduml
