@startuml
set separator ::

enum geo::CubeFace {
	Front  	Back
	Left   	Right
	Top    	Bottom
	All
}
hide CubeFace methods

class geo::GeometryData {
	+positions: Vec3[]
	+colors: Vec3[]
	+uvs: Vec2[]
	+normals: Vec3[]
	..
	+indices: uint[]
}
hide GeometryData methods

class geo::GeometryGenerator {
	{static} +GenerateCube(faces) : GeometryData
}
hide GeometryGenerator fields

class geo::GeometryTransform {
	{static} +ApplyMatrix(&gd, matrix)
	..
	{static} +Scale(&gd, scaleVec)
	{static} +Rotate(&gd, angle, axisVec)
	{static} +Translate(&gd, translationVec)
	..
	{static} +ApplyColor(&gd, color)
}
hide GeometryTransform fields

GeometryGenerator <-right- CubeFace

GeometryData <.up. GeometryGenerator
GeometryData <-right- GeometryTransform

@enduml
